services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=placeholder_key
      - AWS_SECRET_ACCESS_KEY=placeholder_secret
      - AWS_BUCKET_NAME=my-humble-bundles-bucket
      - DISCORD_TOKEN=placeholder_token
      - DISCORD_CHANNEL_ID=716794292600832020
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - salesbundle-network

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: salesbundledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salesbundle-network

volumes:
  postgres_data:

networks:
  salesbundle-network:
    driver: bridge
